### ISSUE TITLE
Question: How might Drake access a user's env? 

### ISSUE THREAD

**Issue by vdice** [lovethedrake/prototype#24]
Wondering if we've thought about how drake/a Drakefile might access a user's environment?

The practical use case that inspired the thought was how we might enable a dev to run `drake run build` (or, `drake run -p build` if defined by a pipeline) and this task/pipeline determining the appropriate, OS-specific build target(s) to run, via utilization of info gleaned from the user's environment.

**Comment by krancour** [comment]
Good question. As for the specific example of getting OS-specific targets to run, there's actually nothing in Drake right now that permits any kind of sophisticated control flow through a pipeline. i.e. You cannot conditionally execute one target or another on the basis of environmental conditions (or any conditions for that matter).

What you _can_ do is move these sort of conditionals into scripts that are invoked in an individual target. So, for instance, it would be quite possible to have a single target that runs a script that uses nested for loops to iterate over OSes and CPU architectures, building for each. You could obtain the list of OSes and CPU architectures from comma-delimited lists sourced from environment variables.

So now the only quest is how a user could define those environment variables to their liking locally (for instance, constraining them to just their _own_ OS and architecture), while allowing those same environment variables to be defined differently (a more extensive list of each) in CI, for instance.

As it turns out, this can already be done. Like much of the rest of Drake, it's not documented yet.

Locally, you can add a `Drakesecrets` file with a `VAR=val` pair per line. You can put whatever you want in here. The Drake CLI will load that and shim those values into all containers it executes. (In the future, I might consider making the format of this file a little more robust to support options like pipeline-specific, target-specific, or container-specific variable).

Elsewhere (not locally; i.e. in Brigade) you can just add secrets to your project and the custom Brigade worker will shim those into your containers.

**Comment by krancour** [comment]
@vdice I'm going to close this. Please feel free to re-open if you think there's still an issue or an opportunity here.
